version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    container_name: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:root@db:5432/ambevapi?schema=public
    depends_on:
      - db
    command: > 
      sh -c "npx prisma migrate deploy && npm run dev"
